### ISSUE TITLE
Couple of styling suggestions to the /docs

### ISSUE THREAD

**Issue by BerkeKaragoz** [gundb/gun-site#57]
## Go from this:
![image](https://user-images.githubusercontent.com/34271483/167613325-22ca47bf-9a33-47cd-af94-e74bb0e3ffa5.png)

## To this:
![image](https://user-images.githubusercontent.com/34271483/167613142-f2e8692c-5adc-4d55-a346-ca0dbe380cef.png)

### Instructions

Put a max-width on articles for readability, see here: [baymard.com/blog/line-length-readability](https://baymard.com/blog/line-length-readability)
```css
.Layout {
    max-width: 75ch; // 75ch seems actually fine for your content
    // and center it
    left: 50%;
    right: 50%;
    transform: translateX(-50%);
    background-color: rgba(0,0,0, 0.2); // highlight the article
}

.show-nav-left .main-container>.Layout {
    width: calc(100% - var(--menu-width))!important;
    transform: translateX(calc(-50% - var(--menu-width)))!important;
    left: calc(50% + var(--menu-width) / 2)!important;
}
```

Increase text opacities:
```css
:root {
  --text-color: rgba(255, 255, 255, .8); // from .51 opacity
  --font-size: 16.8px; // make this the default font size (maybe change the options too)
}

blockquote p {
  color: #ffffff6b; // remove this color, decreases text clarity
} 

blockquote {
  color: #888;
}
```

Remove letter spacings:
```css
.gunlogo {
  //letter-spacing: 4px; // remove
}

.title {
  //letter-spacing: .5rem; // remove
}
```
#### Before
![image](https://user-images.githubusercontent.com/34271483/167613419-660c3595-3f69-48d5-8960-4d8974bc31cc.png)
#### After
![image](https://user-images.githubusercontent.com/34271483/167613202-e2bcb423-ca9c-489c-87a6-29df282d2dbc.png)

#### Before:
![image](https://user-images.githubusercontent.com/34271483/167613463-f645bf08-7c27-4bec-bd5d-80dc81f40540.png)
#### After:
![image](https://user-images.githubusercontent.com/34271483/167613258-0dcc0337-122f-43e1-b776-9ceca36afadd.png)

## Notes

I was going to open up a new branch and submit a pull request. But I think that you are only publishing the build version. I tried to find `.Layout` in the dev css files, but it only found minified files. Therefore I put this up as an issue.

Additionally, for the document structure I recommend using this approach: [codepen.io/BerkeKaragoz/pen/mdqNKME](https://codepen.io/BerkeKaragoz/pen/mdqNKME)
